

export const ActionType = {
    GET_PROFILE_DATA_IS_PENDING: "PROFILE_DATA_IS_PENDING",
    GET_PROFILE_DATA_IS_SUCCESS: "PROFILE_DATA_IS_SUCCESS",
    GET_PROFILE_DATA_IS_FAILURE: "PROFILE_DATA_IS_FAILURE",

    UPDATE_PROFILE_DATA_IS_PENDING:"UPDATE_PROFILE_DATA_IS_PENDING",
    UPDATE_PROFILE_DATA_IS_SUCCESS:"UPDATE_PROFILE_DATA_IS_SUCCESS",
    UPDATE_PROFILE_DATA_IS_FAILURE:"UPDATE_PROFILE_DATA_IS_FAILURE",

    GET_IMAGE_ID_PENDING : "GET_IMAGE_ID_PENDING",
    GET_IMAGE_ID_SUCCESS : "GET_IMAGE_ID_SUCCESS",
    GET_IMAGE_ID_FAILURE : "GET_IMAGE_ID_FAILURE",
}